### ISSUE TITLE
Install an icon before extra-data download

### ISSUE THREAD

**Issue by nedrichards** [flathub/com.flashforge.FlashPrint#1]
We should extract the icon and store it to be used before the extra-data download otherwise you get a broken icon (and sometimes a missing app in some software stores). It can then be overwritten by the one that comes from the archive.

e.g.
https://flathub.org/apps/details/com.flashforge.FlashPrint

**Comment by AsciiWolf** [comment]
Isn't the icon broken because the remote icon url [points](https://github.com/flathub/com.flashforge.FlashPrint/blob/master/com.flashforge.FlashPrint.appdata.xml#L36) to a png icon instead of the correct svg one?

**Comment by AsciiWolf** [comment]
Ah, sorry, you're right. Anyway, renaming the remote icon from png to svg in the AppData file could fix this as well.

**Comment by alexlarsson** [comment]
This was reported as https://github.com/flatpak/flatpak/issues/2857

**Comment by AsciiWolf** [comment]
@Yxogenium Any news?
