### ISSUE TITLE
Unable to Save/Print

### ISSUE THREAD

**Issue by birb7** [flathub/com.flashforge.FlashPrint#21]
Os: Arch, Artix, Void, Debian 11

Reproduction:
-open stl model
-slice model
-click save/ctrl+s/save as/save project

Results: no prompt for saving file
Expected result: a file manager to appear allowing me to choose a location and filename to save

What I Tried: overriding flatpak file permissions in root, running flatseal in root and allowing home and host filesystem

**Comment by hadess** [comment]
Works fine on Fedora 36 desktop using GNOME. Make sure the `xdg-desktop-portal` packages for your desktop are correctly installed.

**Comment by birb7** [comment]
my package manager said 'xdg-desktop-portal-kde' was already installed

**Comment by birb7** [comment]
> 

well then, i did some more reading into flatpak and xdg and i needed another package called just 'xdg-desktop-portal' without the '-kde' added
