### ISSUE TITLE
org.kde.Platform//5.15 is end-of-life

### ISSUE THREAD

**Issue by MaceMoneta** [flathub/com.flashforge.FlashPrint#22]
flatpak update

Looking for updates…
Info: org.kde.Platform//5.15 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Applications using this runtime:
   com.flashforge.FlashPrint

**Comment by hadess** [comment]
The newer versions of the runtime don't have Qt5, so we can't update them:
https://bugs.kde.org/show_bug.cgi?id=452356

**Comment by hadess** [comment]
Untested fix:
https://github.com/flathub/com.flashforge.FlashPrint/pull/23
